import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "./shared/Navbar";
import { getServerSession } from "next-auth";
import Provider from "@/provider/Provider";
import { authOptions } from "./utils/authOptions";
import { ThemeProvider } from "next-themes";
import "@uploadthing/react/styles.css";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Drizzle Crud",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="container mx-auto">
          
            <Provider session={session}>
              <Navbar />
              <Toaster position="top-right" duration={1000} />
              
                {children}
              
            </Provider>
            
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
